version: "3.3"

services:
  backend:
    build: ./backend
    working_dir: /var/app
    environment:
      NODE_ENV: development
      DISCORD_TOKEN: ${CCAUDIO_DISCORD_TOKEN}
    ports:
      - "80:8080"